// Generated by CoffeeScript 1.7.1
(function() {
  var _base,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Movie || (window.Movie = {});

  (_base = window.Movie).Views || (_base.Views = {});

  Movie.Views.MainDisplayView = (function(_super) {
    __extends(MainDisplayView, _super);

    function MainDisplayView() {
      this.setPlayerName = __bind(this.setPlayerName, this);
      this.setVsView = __bind(this.setVsView, this);
      this.launchMultiplayer = __bind(this.launchMultiplayer, this);
      this.setPlayerAsReady = __bind(this.setPlayerAsReady, this);
      this.setPlayerNumber = __bind(this.setPlayerNumber, this);
      this.pulsate = __bind(this.pulsate, this);
      this.parseMessage = __bind(this.parseMessage, this);
      return MainDisplayView.__super__.constructor.apply(this, arguments);
    }

    MainDisplayView.prototype.initialize = function() {
      this.loadCastRequirements();
      this.playerOne = {
        ready: false,
        name: null
      };
      return this.playerTwo = {
        ready: false,
        name: null
      };
    };

    MainDisplayView.prototype.loadCastRequirements = function() {
      cast.receiver.logger.setLevelValue(cast.receiver.LoggerLevel.DEBUG);
      this.castReceiverManager = cast.receiver.CastReceiverManager.getInstance();
      this.customMessageBus = this.castReceiverManager.getCastMessageBus('urn:x-cast:movie.quote.game');
      this.castReceiverManager.onSenderConnected = this.senderConnected;
      this.castReceiverManager.start();
      return this.customMessageBus.onMessage = this.parseMessage;
    };

    MainDisplayView.prototype.parseMessage = function(e) {
      var message;
      message = JSON.parse(e.data);
      if (message.displayMessage) {
        this.displayMessage = message.displayMessage;
        if (this.message != null) {
          window.clearInterval(this.message);
        }
        this.message = window.setInterval(this.pulsate, 700);
      }
      if (message.playerNumber) {
        this.setPlayerNumber(message.playerNumber);
      }
      if (message.setPlayerName) {
        this.setPlayerName(message.setPlayerName, e.senderId);
      }
      if (message.ready) {
        return this.setPlayerAsReady(e.senderId);
      }
    };

    MainDisplayView.prototype.pulsate = function() {
      $("#message").html(this.displayMessage);
      return $("#message").fadeToggle();
    };

    MainDisplayView.prototype.setPlayerNumber = function(numberOfPlayers) {
      if (numberOfPlayers === 'single-player') {
        return setTimeout((function(_this) {
          return function() {
            return _this.customMessageBus.broadcast("start");
          };
        })(this), 2000);
      } else {
        return this.launchGame = window.setInterval(this.launchMultiplayer, 4000);
      }
    };

    MainDisplayView.prototype.setPlayerAsReady = function(playerId) {
      if (this.playerOne.senderId === playerId) {
        return this.playerOne.ready = true;
      } else {
        return this.playerTwo.ready = true;
      }
    };

    MainDisplayView.prototype.launchMultiplayer = function() {
      if (this.playerOne.ready && this.playerTwo.ready) {
        window.clearInterval(this.launchGame);
        this.launchGame = 0;
        this.setVsView();
        return setTimeout((function(_this) {
          return function() {
            return _this.customMessageBus.broadcast("start");
          };
        })(this), 2500);
      }
    };

    MainDisplayView.prototype.setVsView = function() {
      $('#player1').html(this.playerOne.name);
      $('#player2').html(this.playerTwo.name);
      $('.logo-area').addClass("hidden");
      return setTimeout((function(_this) {
        return function() {
          return $('.vs-view').fadeIn();
        };
      })(this), 200);
    };

    MainDisplayView.prototype.setPlayerName = function(name, senderId) {
      if (this.playerOne.name != null) {
        this.playerTwo.name = name;
        return this.playerTwo.senderId = senderId;
      } else {
        this.playerOne.name = name;
        return this.playerOne.senderId = senderId;
      }
    };

    MainDisplayView.prototype.senderConnected = function(e) {};

    return MainDisplayView;

  })(Backbone.View);

}).call(this);
